[package]
name = "flytile"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
rocket = "0.5.1"
tokio = { version = "1.43.0", features = ["sync"] }
zip = "2.2.2"
